#!/bin/bash
D=$(dirname $0)

rm -f .config
make -C ../buildroot  BR2_EXTERNAL=$(pwd) O=$(pwd) defconfig

FRAGMENTS=()
if [[ $1 =~ ^arm.* ]]; then
  FRAGMENTS+=("arm")
fi

FRAGMENTS+=("base")
FRAGMENTS+=("$*") # ensure passed-in frags override base

echo "using fragments: " ${FRAGMENTS[@]}
for frag in ${FRAGMENTS[@]}; do
  if [ -e $D/configs/frags/$frag.config ]; then
    echo "INFO: Including fragment: $frag"
    cat $D/configs/frags/$frag.config >> .config
  else
    echo "WARNING: $D/configs/frags/$frag.config doesn't exist.  Giving up."
    exit 1
  fi
done

# reconfigure with new fragments appended
make olddefconfig

make

RESULT=$?
if [ $RESULT != 0 ]; then
    exit $RESULT
fi

# remove uncompressed versions of rootfs
(cd images; rm -f rootfs.cpio rootfs.tar rootfs.ext2)

if [ $? = 0 ]; then
    echo "Packaging up output/host directory"
    tar -C output/host -Jcf output/images/host.tar.xz .
    (cd output/images; md5sum host.tar.xz > host.tar.xz.md5)
fi
