#!/bin/bash
D=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

git submodule init
git submodule update

rm -rf output
mkdir output
pushd output

make -C ../buildroot  BR2_EXTERNAL=../buildroot-external O=$(pwd) defconfig

FRAGMENTS=()
if [[ $1 =~ ^arm.* ]]; then
  FRAGMENTS+=("arm")
fi

FRAGMENTS+=("base")
FRAGMENTS+=("$*") # ensure passed-in frags override base

echo "using fragments: " ${FRAGMENTS[@]}
for frag in ${FRAGMENTS[@]}; do
  if [ -e $D/buildroot-external/configs/frags/$frag.config ]; then
    echo "INFO: Including fragment: $frag"
    cat $D/buildroot-external/configs/frags/$frag.config >> .config
  else
    echo "WARNING: $D/buildroot-external/configs/frags/$frag.config doesn't exist.  Giving up."
    exit 1
  fi
done

# reconfigure with new fragments appended
make olddefconfig

make

RESULT=$?
if [ $RESULT != 0 ]; then
    exit $RESULT
fi

# remove uncompressed versions of rootfs
(cd images; rm -f rootfs.cpio rootfs.tar rootfs.ext2)

if [ $? = 0 ]; then
    echo "Packaging up output/host directory"
    tar -C host -Jcf images/host.tar.xz .
    (cd images; md5sum host.tar.xz > host.tar.xz.md5)
fi
